### PR TITLE
docs: drop broken conda badge

### PR DESCRIPTION
**Pull request by henryiii**
Pretty sure this isn't supposed to be on conda-forge?

### CODE REVIEW

**Comment by kratsg** [comment]
> Pretty sure this isn't supposed to be on conda-forge?

a reminder for me to have added it 🤣 but... i don't know if I want to bother getting it on conda-forge now.

**Comment by henryiii** [comment]
Generally the original lib should be on conda-forge, it doesn't need to be a wrapper.

**Comment by kratsg** [comment]
I see https://anaconda.org/conda-forge/python-magic but it's only sdists as far as I can tell. It doesn't ship a cross-compiled lib (hence this package).

**Comment by kratsg** [comment]
> Then you should probably make `magic-feedstock` or `libmagic-feedstock` that builds this, but it doesn't need the PyPI wrapping, conda supports native libraries.

What is pypi wrapping here? I guess I'm not sure I follow. Don't I still need to cross-compile, or does conda handle that if I give it the package itself?

**Comment by henryiii** [comment]
You'll set up a recipe, and in that recipe you'd be setting up the package. You don't need to make it importable or installable via `pip`. Conda-forge directly can run the shell commands required to build with autotools (or cmake, etc).

**Pull request merged**
